services:
  app:
    build: .
    container_name: hifiy_backend
    ports:
      - "8081:8082" 
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db: 
    image: postgres:15-alpine
    container_name: hifiy_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: dbcoffeshop
    ports:
      - "5434:5432"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: hifiy_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6378:6379"
    restart: always
